### ISSUE TITLE
It freezes on the message: Spinning up the fork server...

### ISSUE THREAD

**Issue by cristiandaniele** [stateafl/stateafl#14]
By following the guideline step by step, I cannot run stateafl on LightFTP. stateafl freezes before starting the fuzzing campaign on the message: " Spinning up the fork server...".

**Comment by Thibault-Van-Win** [comment]
Might be the same issue as https://github.com/stateafl/stateafl/issues/7

**Comment by cristiandaniele** [comment]
Good point! I missed your thread! Thanks!:)
