### ISSUE TITLE
"Error: no messages found" when converting demo PCAP file

### ISSUE THREAD

**Issue by Thibault-Van-Win** [stateafl/stateafl#5]
I was trying to recreate the demo by setting up a LightFtp server and capturing the messages. For this I followed the demo transcript, but when i tried to convert it to replay format, the script keeps running into the error: "No messages found".

Here you can find the [ftp.zip](https://github.com/stateafl/stateafl/files/10940603/ftp.zip) pcap. When inspecting this with Wireshark, it is clear that the pcap only contains 1 message flow as can be seen on the picture below:

![Screenshot from 2023-03-10 10-38-56](https://user-images.githubusercontent.com/70701521/224280992-93530e32-0950-43ae-ae86-9b42df5fb4e6.png)

For the conversion I used: `python3 convert-pcap-replay-format.py --input ftp.pcap --server-port 2200 --client-port 55450 --output ftp.replay --ignore-multiple-clients`

Thanks in advance!

**Comment by rnatella** [comment]
Dear Thibault

I am unable to reproduce your problem. The script can correctly identify FTP requests and generate a replay file.
Find below the output and the resulting file

```
$ python3 convert-pcap-replay-format.py --input ../ftp.pcap --server-port 2200 --client-port 55450 --output ftp.replay --ignore-multiple-clients
Writing 15 bytes...
Writing 14 bytes...
Writing 6 bytes...
Writing 5 bytes...
Writing 10 bytes...
Writing 10 bytes...
Writing 5 bytes...
Writing 6 bytes...
Converted PCAP saved to ftp.replay
```


[ftp.replay.zip](https://github.com/stateafl/stateafl/files/10942683/ftp.replay.zip)

**Comment by Thibault-Van-Win** [comment]
After some debugging, I found that `len(request_msg) > 0` always return 0 in the final if-statement of the last try catch.

This means that the `request_msg` is never extended because the packets do not have an attribute data.
When printing these packets they indeed did not contain a `data` field, but some did include a `DATA` field shown in the picture below.

![image](https://user-images.githubusercontent.com/70701521/224842064-7e3efd0a-e52b-4c9f-84b5-c4fd9d2acd2d.png)

Changing the line `request_msg.extend(pkt.data.data.binary_value)` to `request_msg.extend(pkt.DATA.data.binary_value)` did the trick. Now it converts the pcap file correctly.
